### ISSUE TITLE
Improve translatability

### ISSUE THREAD

**Issue by humdingerb** [janus2/WordClock#3]
As discussed at https://discuss.haiku-os.org/t/help-translating-applications-with-polyglot/6548/98?u=humdinger

I experimentally did the German translation once. The (potential) problem is that translations use differently long words. The words per line and their order is fixed. On top of that, there may be idiosyncrasies of languages so there are more (or less) words than “quarter to/past”, or we need a different order etc.

This would be the German version as is:

![wordclock-de](https://user-images.githubusercontent.com/6107158/207020482-62ac7660-7b54-48fc-9b75-526fe79c3359.png)

As you can see, the “fünf Minuten vor” looks quite cramped.

**Comment by Begasus** [comment]
Should be fixed in: https://github.com/janus2/WordClock/pull/4

![Word-Clock-NL](https://user-images.githubusercontent.com/16057090/207043056-09458ca8-fefa-4f3a-8392-a8afa753fb1c.png)

**Comment by humdingerb** [comment]
Doesn't fix the underlying general problem of locales that might be sufficiently different when it comes to express time.

**Comment by Begasus** [comment]
Maybe it doesn't fix everything, but it's a start at least :)
Maybe an example on what is wrong?

**Comment by humdingerb** [comment]
Let's see what @janus2 says. Haven't seen him in a while... Hope you're alright,buddy.
